[package]
name = "pset"
version = "0.1.0"
edition = "2021"
authors = ["Marius Wörfel"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
sailfish = "0.8.3"
